### ISSUE TITLE
Whether you have code about translation

### ISSUE THREAD

**Issue by wyw97** [abdfahim/audioprocessing#1]
I have been following your research group for a long time. I am engaged in the translation of SH coefficients, especially the paper by Samarasinghe, which inspired me a lot. If you or your research group can release the code about the translation of the sphere harmonics analysis. Thanks so much!

**Comment by abdfahim** [comment]
Hi, you might want to directly get in touch with the AASP research group at ANU from the following link:
https://cecc.anu.edu.au/research/information/audio-acoustic-signal-processing#acton-tabs-link--tabs-0-row_2-2
